
is.empty <- function(x){
  return(length(x) == 0)
}

prange <- function(start, end){
  if(end >= start){
    return(range(start, end))
  } else {
    return(c())
  }
}

multigsub = function(replacements = c(), patterns = c(), txt){
  out = txt
  if(length(replacements) > 0){
    for(i in 1:length(replacements)){
      out = gsub(replacements[i], patterns[i], out)
    }
  }
  return(out)
}

#readDeploymentOptions <- function(){
#  source(file = "deploy/deploy_options.R", local=TRUE)
#  return(deployment_options)
#}

deploymentOptionSpecs <- list(
  "deployment_mode" = list(global = "RokaiXplorer_deployment_mode", required = FALSE, default = FALSE),
  "data_file_path" = list(global = "RokaiXplorer_data_filepath", required = FALSE, default = "data/rokaiXplorer_sample_data.csv"),
  "metadata_file_path" = list(global = "RokaiXplorer_metadata_filepath", required = FALSE, default = "data/rokaiXplorer_sample_metadata.csv"),
  "expression_data_file_path" = list(global = "RokaiXplorer_expression_data_filepath", required = FALSE, default = NULL),
  "use_expression_data" = list(global = "RokaiXplorer_use_expression_data", required = FALSE, default = FALSE),
  "config_file_path" = list(global = "RokaiXplorer_config_file_path", required = FALSE, default = "deploy/config.json"),
  "reference_proteome" = list(global = "RokaiXplorer_reference_proteome", required = FALSE, default = "Uniprot Mouse"),
  "application_title" = list(global = "RokaiXplorer_application_title", required = FALSE, default = "ExampleApp"),
  "application_subtitle" = list(global = "RokaiXplorer_application_subtitle", required = FALSE, default = "This is a sample application generated by RokaiXplorer"),
  "description_file_path" = list(global = "RokaiXplorer_description_filepath", required = FALSE, default = "deploy/description.md"),
  "extra_resources_folder" = list(global = "RokaiXplorer_resources_folder", required = FALSE, default = NULL),
  "shinyapps_title" = list(global = "RokaiXplorer_shinyapps_title", required = FALSE, default = NULL),
  "shinyapps_account" = list(global = "RokaiXplorer_shinyapps_account", required = FALSE, default = NULL),
  "allow_data_download" = list(global = "RokaiXplorer_allow_data_download", required = FALSE, default = TRUE),
  "." = NULL
);

readDeploymentOptions <- function(wd = getwd()){
  tryCatch(
    source(file = sprintf("%s/deploy/deploy_options.R", wd), local=TRUE), 
    error = function(e) {
      # message(e)
    })
  # This loads a list named 'deployment_options' 
  
  if(!exists("deployment_options")){
    deployment_options <- list()
  }
  
  opts <- names(deploymentOptionSpecs)
  for(iOpt in (1:(length(deploymentOptionSpecs) - 1))){
    name = opts[[iOpt]]
    l = deploymentOptionSpecs[[iOpt]]
    global_name = l$global
    value = getOption(global_name)
    if(!is.null(value) && !is.na(value)){
      deployment_options[[name]] = value
    } else {
      if(is.null(deployment_options[[name]])){
        deployment_options[[name]] = l$default
      }
    }
  }
  
  return(deployment_options)
}